include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    enable-experiment:
      - null-aware-elements
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/build/**"
    - "**/.dart_tool/**"
    - "**/coverage/**"
    - "**/templates/**"
    - "**/__brick__/**"
