targets:
  $default:
    sources:
      exclude:
        - "**/tool/integration_scenarios/**"
        - "packages/fly_cli/tool/integration_scenarios/**"
        - "tool/integration_scenarios/**"
    builders:
      freezed:
        generate_for:
          exclude:
            - "**/tool/integration_scenarios/**"
            - "packages/fly_cli/tool/integration_scenarios/**"
            - "tool/integration_scenarios/**"
      json_serializable:
        generate_for:
          exclude:
            - "**/tool/integration_scenarios/**"
            - "packages/fly_cli/tool/integration_scenarios/**"
            - "tool/integration_scenarios/**"

