name: {{project_name_snake}}
description: {{description}}
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Fly CLI Foundation Packages
  fly_core:
    path: ../../packages/fly_core
  fly_networking:
    path: ../../packages/fly_networking
  fly_state:
    path: ../../packages/fly_state
  
  # State Management
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.0
  
  # Navigation
  go_router: ^12.1.0
  
  # Utilities
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^3.0.0
  freezed: ^3.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
