name: fly_mcp_server
description: MCP Server runtime for Fly CLI. Exposes tools, resources, and prompts over stdio.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dart_mcp: ^0.3.3
  meta: ^1.12.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0

