name: fly_mcp_core
description: Core MCP (Model Context Protocol) primitives for Fly CLI – JSON-RPC over stdio, framing, and protocol types.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.12.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0

