name: fly_core
description: Core foundation package for Fly CLI with BaseScreen, BaseViewModel, and common utilities
version: 0.1.0
homepage: https://github.com/fly-cli/fly
repository: https://github.com/fly-cli/fly.git
issue_tracker: https://github.com/fly-cli/fly/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.10.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.7
  riverpod_generator: ^3.0.0
  freezed: ^3.0.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
