/// Result of executing a single brick generation.
///
/// This is a generic result type that doesn't depend on CLI-specific
/// file representations. The type parameter `TFile` allows different
/// hosts (CLI, test harnesses, etc.) to use their own file types.
class BrickExecutionResult<TFile> {
  const BrickExecutionResult._({
    required this.success,
    this.files,
    this.error,
  });

  /// Creates a successful result with generated files.
  factory BrickExecutionResult.success({required List<TFile> files}) {
    return BrickExecutionResult._(
      success: true,
      files: files,
    );
  }

  /// Creates a failed result with an error message.
  factory BrickExecutionResult.failure({required String error}) {
    return BrickExecutionResult._(
      success: false,
      error: error,
    );
  }

  /// Whether the brick execution succeeded.
  final bool success;

  /// List of files generated by the brick (if successful).
  final List<TFile>? files;

  /// Error message (if failed).
  final String? error;
}

/// Abstract interface for executing brick generation.
///
/// This interface abstracts away the concrete implementation details
/// of how bricks are executed (e.g., via Mason, file copying, etc.).
/// Different hosts (CLI, tests, etc.) implement this interface to
/// provide their own execution strategy.
///
/// The type parameter `TFile` allows hosts to use their own file
/// representations (e.g., `GeneratedFile` in CLI, `String` paths in tests).
abstract class BrickExecutor<TFile> {
  /// Executes a brick generation with the given parameters.
  ///
  /// [brickId] is the identifier of the brick to execute (e.g., 'fly_foundation_project').
  /// [vars] is the map of variables to pass to the brick template.
  /// [targetDirectory] is the absolute path where the brick should generate files.
  ///
  /// Returns a [BrickExecutionResult] indicating success or failure.
  Future<BrickExecutionResult<TFile>> executeBrick({
    required String brickId,
    required Map<String, dynamic> vars,
    required String targetDirectory,
  });
}

