name: service
description: Fly foundation service scaffolding brick for generating API, local, cache, analytics, and storage services
version: 1.0.0
homepage: https://github.com/fly-cli/fly
repository: https://github.com/fly-cli/fly.git
issue_tracker: https://github.com/fly-cli/fly/issues
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

