name: fly_cli
description: AI-native Flutter CLI tool for project scaffolding
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0
  path: ^1.8.3
  http: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.4.2

# Export src directory
