name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dart-version: [stable]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-version }}
      
      - name: Install dependencies
        run: dart pub get
        working-directory: packages/fly_cli
      
      - name: Run tests
        run: dart test
        working-directory: packages/fly_cli
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.os }}
          path: packages/fly_cli/test-results/
          if-no-files-found: ignore

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      
      - name: Install dependencies
        run: dart pub get
        working-directory: packages/fly_cli
      
      - name: Analyze code
        run: dart analyze
        working-directory: packages/fly_cli
      
      - name: Check formatting
        run: dart format --set-exit-if-changed .
        working-directory: packages/fly_cli
